services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: ['server', '--console-address', ':9001', '/data']
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    labels:
      - "traefik.docker.network=traefik-ingress"
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entryPoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`minio.hive.beabee.io`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certResolver=letsencrypt"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=oauthAuth@file,secHeaders@file"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=9001"
    networks:
      - storage-network
      - traefik-ingress

volumes:
  minio_data:

networks:
  storage-network:
    external: true
  traefik-ingress:
    external: true
