version: '3.8'

services:
  postgres-1:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_16_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - db-network
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres_16_data:

networks:
  db-network:
    external: true
